force-app/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Serie__c/Activity_Serie__c.object-meta.xml
<CustomObject>
    <label>Task Series</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Serie__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Task_Series</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Serie__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipName>Task_Series</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Serie__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Task_Series</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TaskSerieHandler.cls
public with sharing class TaskSerieHandler {
    @AuraEnabled
    public static string createNewTaskSerie(string name, string accountId, string opportunityId, string accountPlanId, string comment){
        try{
            Activity_Serie__c taskSerie = new Activity_Serie__c(
                Name = name
            );

            if(!String.isBlank(accountid)){
                taskSerie.Account__c = id.valueOf(accountId);
            }

            if(!String.isBlank(opportunityId)){
                taskSerie.Opportunity__c = id.valueOf(opportunityId);
            }

            if(!String.isBlank(accountPlanId)){
                taskSerie.Account_Plan__c = id.valueOf(accountPlanId);
            }

            if(!String.isBlank(comment)){
                taskSerie.Comments__c = comment;
            }
            
            insert taskSerie;

            return taskSerie.id;
        } catch(Exception e){
            return 'error ' + e.getMessage();
        }
    }
}