force-app/main/default/objects/Opportunity_Stakeholder__c/Opportunity_Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Opportunity Stakeholder</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Stakeholders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Stakeholder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Stakeholders</relationshipLabel>
    <relationshipName>Opportunity_Stakeholders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Stakeholder__c/fields/Stakeholder__c.field-meta.xml
<CustomField>
    <fullName>Stakeholder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stakeholder</label>
    <referenceTo>Stakeholder__c</referenceTo>
    <relationshipLabel>Opportunity Stakeholders</relationshipLabel>
    <relationshipName>Opportunity_Stakeholders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Stakeholder</label>
    <nameField>
        <label>Stakeholder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OpportunityStakeHolderTriggerHandlerTest.cls
@isTest

public class OpportunityStakeHolderTriggerHandlerTest {
    
    @isTest static void beforeInsertTest(){
        Stakeholder__c stk= TestDataFactory.createStakeholderWithoutCreate();
        insert stk;
        
        Opportunity opp= TestDataFactory.createOppWithAccountWithAddress('OpportunityStakeHolderTrigHand, beforeInsert');
        
        Opportunity_Stakeholder__c  opp_stk = new Opportunity_Stakeholder__c(Name='TestOpp Stakeholder',Opportunity__c =opp.Id, Stakeholder__c = stk.Id);
        insert opp_stk;
        
        
        Test.startTest();
        Opportunity_Stakeholder__c acc_St = [select Id,Stakeholder__c from Opportunity_Stakeholder__c where Id=:opp_stk.Id];
        System.assertEquals(acc_St.Stakeholder__c, stk.Id);
        Test.stopTest();
    }

}