force-app/main/default/objects/Opportunity_Stakeholder__c/Opportunity_Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Opportunity Stakeholder</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Stakeholders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Stakeholder__c/fields/Stakeholder__c.field-meta.xml
<CustomField>
    <fullName>Stakeholder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stakeholder</label>
    <referenceTo>Stakeholder__c</referenceTo>
    <relationshipLabel>Opportunity Stakeholders</relationshipLabel>
    <relationshipName>Opportunity_Stakeholders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Stakeholder</label>
    <nameField>
        <label>Stakeholder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OpportunityStakeHolderTriggerHandler.cls
public with sharing class OpportunityStakeHolderTriggerHandler {
    public static void beforeInsert(List<Opportunity_Stakeholder__c> accStakeHoldersArg){
        
        mapFields(accStakeHoldersArg);

    }
    public static void mapFields(List<Opportunity_Stakeholder__c> accStakeHoldersArg){
        Set<Id> stakeholderIds = new Set<Id>();
        for(Opportunity_Stakeholder__c accstakeLooper : accStakeHoldersArg){
            stakeholderIds.add(accstakeLooper.Stakeholder__c);
        }
        Map<Id, Stakeholder__c> newMap = new Map<Id, Stakeholder__c>([SELECT Id, Name FROM Stakeholder__c WHERE Id IN :stakeholderIds]);

        System.debug('map 1');

        for(Opportunity_Stakeholder__c oshLooper : accStakeHoldersArg){
        System.debug('map 2');
        System.debug(newMap.size());
            oshLooper.name = newMap.get(oshLooper.Stakeholder__c).Name;
        }
    }
}