force-app/main/default/objects/Account_Stakeholder__c/Account_Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Account Stakeholder</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Stakeholder</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Stakeholder__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Stakeholder_Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Stakeholder__c/fields/Stakeholder__c.field-meta.xml
<CustomField>
    <fullName>Stakeholder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stakeholder</label>
    <referenceTo>Stakeholder__c</referenceTo>
    <relationshipName>Stakeholder_Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Stakeholder</label>
    <nameField>
        <label>Stakeholder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountStakeHolderTriggerHandlerTest.cls
@isTest
public class AccountStakeHolderTriggerHandlerTest {
    
    @isTest static void beforeInsertTest(){
        Stakeholder__c stk= TestDataFactory.createStakeholderWithoutCreate();
        insert stk;
        
        Account acc= TestDataFactory.createSingelAccount();
        
        Account_Stakeholder__c  acct_stk = new Account_Stakeholder__c(Name='TestAccount Stakeholder',Account__c =acc.Id, Stakeholder__c = stk.Id);
        insert acct_stk;
        
        
        Test.startTest();
        Account_Stakeholder__c acc_St = [select Id,Stakeholder__c from Account_Stakeholder__c where Id=:acct_stk.Id];
        System.assertEquals(acc_St.Stakeholder__c, stk.Id);
        Test.stopTest();
    }

}