force-app/main/default/objects/Account_Stakeholder__c/Account_Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Account Stakeholder</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Stakeholder</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Stakeholder__c/fields/Stakeholder__c.field-meta.xml
<CustomField>
    <fullName>Stakeholder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stakeholder</label>
    <referenceTo>Stakeholder__c</referenceTo>
    <relationshipName>Stakeholder_Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Stakeholder</label>
    <nameField>
        <label>Stakeholder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountStakeHolderTriggerHandler.cls
public with sharing class AccountStakeHolderTriggerHandler {
    public static void beforeInsert(List<Account_Stakeholder__c> accStakeHoldersArg){
        
        mapFields(accStakeHoldersArg);

    }
    public static void mapFields(List<Account_Stakeholder__c> accStakeHoldersArg){
        Set<Id> stakeholderIds = new Set<Id>();
        for(Account_Stakeholder__c accstakeLooper : accStakeHoldersArg){
            stakeholderIds.add(accstakeLooper.Stakeholder__c);
        }
        Map<Id, Stakeholder__c> newMap = new Map<Id, Stakeholder__c>([SELECT Id, Name FROM Stakeholder__c WHERE Id IN :stakeholderIds]);

        System.debug('map 1');

        for(Account_Stakeholder__c ashLooper : accStakeHoldersArg){
        System.debug('map 2');
        System.debug(newMap.size());

            ashLooper.name = newMap.get(ashLooper.Stakeholder__c).Name;
        }
    }
}