force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Account_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_Type__c.field-meta.xml
<CustomField>
    <fullName>Address_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address Type</label>
    <referenceTo>Address_Type__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address_Type__c/Address_Type__c.object-meta.xml
<CustomObject>
    <label>Address Type</label>
    <nameField>
        <label>Address Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/QuoteTriggerHandlerTest.cls
@isTest
public class QuoteTriggerHandlerTest {
    
    @isTest static void beforeInsertTest(){
        Account acc = TestDataFactory.createAccountWithAddresses();
        Opportunity opp = TestDataFactory.createOpportunity(acc);
        Quote quote = TestDataFactory.createQuote(acc, opp);
        Address__c billto = [SELECT Id FROM Address__c WHERE Account__c =: acc.Id AND Address_Type__r.Name = 'Bill-to'];
        quote.Name = 'TestQuote updated';
        quote.Bill_to__c = billto.Id;
        System.debug(billto.Id);
        update quote;
        
        Test.startTest();
        Quote qt = [SELECT Id,Name,OpportunityId FROM Quote where Id=:quote.Id];
        System.assertEquals(qt.Name, 'TestQuote updated');
        Test.stopTest();
    }

}