force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country_code_3__c.field-meta.xml
<CustomField>
    <fullName>Country_code_3__c</fullName>
    <label>Country code (3)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Alpha_2_Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_2_Code__c</fullName>
    <label>Alpha-2 Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>All_countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/All_countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AS</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BQ</fullName>
    </customValue>
    <masterLabel>All Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AddressTriggerHandler.cls
public with sharing class AddressTriggerHandler {
    public static void beforeInsert(List<Address__c> addressesArg){
       mapFields(addressesArg);
    }
    public static void beforeUpdate(List<Address__c> addressesArg){
       mapFields(addressesArg);
    }

    public static void mapFields(List<Address__c> addressesArg){
        List<Country__c> countryList = [SELECT Id, Name, Alpha_2_Code__c FROM Country__c];
        Map<String, Id> countryNameToCountryIdMap = new Map<String, Id>();
        for(Country__c country : countryList){
            countryNameToCountryIdMap.put(country.Alpha_2_Code__c, country.id);
        }
        for(Address__c addressLooper: addressesArg){
            String alpha2Code = addressLooper.Address__countryCode__s;
            if(countryNameToCountryIdMap.get(alpha2Code) != null){
                addressLooper.Country__c = countryNameToCountryIdMap.get(alpha2Code);
            }
            if(addressLooper.Nickname__c != null){
                addressLooper.Name = addressLooper.Nickname__c;
            }
            else {
                addressLooper.Name = addressLooper.Address__Street__s + ',' + addressLooper.Address__City__s + ',' + addressLooper.Address__countryCode__s;
            }
            System.debug('Address1: '+addressLooper.Address__CountryCode__s);
            if(addressLooper.Address__CountryCode__s == null) continue;
            addressLooper.Country_code_3__c =  FieldMappingTables.getThreeCharCountryCode(addressLooper.Address__CountryCode__s);
        }
    }
}