force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Account_Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <label>Legacy Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <label>Legacy Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_3__c</fullName>
    <label>Legacy Address Line 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Postal_code__c.field-meta.xml
<CustomField>
    <fullName>Postal_code__c</fullName>
    <label>Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Alpha_2_Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_2_Code__c</fullName>
    <label>Alpha-2 Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>All_countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/All_countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AS</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BQ</fullName>
    </customValue>
    <masterLabel>All Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityClass.cls
/**
 * @description       : 
 * @author            : Ahmad Nawaz
 * @group             : 
 * @last modified on  : 19-09-2022
 * @last modified by  : Ahmad Nawaz
 * Modifications Log 
 * Ver   Date         Author        Modification
 * 1.0   25-11-2022   Ahmad Nawaz   Initial Version
 * Tested By : OpportunityTriggerHandlerTest
**/
public with sharing class OpportunityClass {
    public static void connectBilltoAddresses(Opportunity opportunityInc, Address__c addressInc){
        if(addressInc.Address__City__s != null) opportunityInc.Bill_To_Address__City__s = addressInc.Address__City__s;
        if(addressInc.Address__countryCode__s != null) opportunityInc.Bill_To_Address__countryCode__s = addressInc.Address__countryCode__s;
        if(addressInc.Address__postalCode__s != null) opportunityInc.Bill_To_Address__postalCode__s = addressInc.Address__postalCode__s;
        if(addressInc.Address__StateCode__s != null) opportunityInc.Bill_To_Address__StateCode__s = addressInc.Address__StateCode__s;
        if(addressInc.Address__Street__s != null) opportunityInc.Bill_To_Address__Street__s = addressInc.Address__Street__s;
        if(addressInc.Address_Line_1__c != null) opportunityInc.Bill_to_Address_1__c = addressInc.Address_Line_1__c;
        if(addressInc.Address_Line_2__c != null) opportunityInc.Bill_to_Address_2__c = addressInc.Address_Line_2__c;
        if(addressInc.Address_Line_3__c != null) opportunityInc.Bill_to_Address_3__c = addressInc.Address_Line_3__c;
        if(addressInc.Postal_code__c != null) opportunityInc.Bill_to_Postal_code__c = addressInc.Postal_code__c;
        if(addressInc.Id != null) opportunityInc.Bill_to__c = addressInc.Id;
    }
    
    public static void connectShiptoAddresses(Opportunity opportunityInc, Address__c addressInc){
        if(addressInc.Address__City__s != null) opportunityInc.Ship_To_Address__City__s = addressInc.Address__City__s;
        if(addressInc.Address__countryCode__s != null) opportunityInc.Ship_To_Address__countryCode__s = addressInc.Address__countryCode__s;
        if(addressInc.Address__postalCode__s != null) opportunityInc.Ship_To_Address__postalCode__s = addressInc.Address__postalCode__s;
        if(addressInc.Address__Street__s != null) opportunityInc.Ship_To_Address__Street__s = addressInc.Address__Street__s;
        if(addressInc.Address__StateCode__s != null) opportunityInc.Ship_To_Address__StateCode__s = addressInc.Address__StateCode__s;

        opportunityInc.Ship_to__c = addressInc.Id;
    }
    /*@AuraEnabled
    public static String generateOpportunityName(Id accIdInc){
        try {
            Account acc = [SELECT Id, Customer__r.Name FROM Account WHERE Id = :accIdInc];
            Address__c addr = [SELECT Id, Country__r.Alpha_2_Code__c FROM Address__c WHERE Account__c =:acc.Id];
            String oppName = acc.Customer__r.Name + '-' + addr.Country__r.Alpha_2_Code__c;
            return oppName;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }*/
}