force-app/main/default/objects/Visit_Report__c/Visit_Report__c.object-meta.xml
<CustomObject>
    <description>As a user I want to be able to add a visit report with all needed information So I can keep my visit notes in a structured way</description>
    <label>Visit Report</label>
    <nameField>
        <label>Visit Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Report__c/fields/Accomplishments__c.field-meta.xml
<CustomField>
    <fullName>Accomplishments__c</fullName>
    <label>Accomplishments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Visit_Report__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visit Reports</relationshipLabel>
    <relationshipName>Visit_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Report__c/fields/Additional_attendance_to_the_meeting__c.field-meta.xml
<CustomField>
    <fullName>Additional_attendance_to_the_meeting__c</fullName>
    <label>Additional attendance to the meeting</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Report__c/fields/Agenda_of_visit__c.field-meta.xml
<CustomField>
    <fullName>Agenda_of_visit__c</fullName>
    <label>Agenda of visit</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Visit_Report__c/fields/Attendance_Contact_person_in_meeting__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Contact_person_in_meeting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attendance: Contact person in meeting</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Visit Reports</relationshipLabel>
    <relationshipName>Visit_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Report__c/fields/Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_Time__c</fullName>
    <label>Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit_Report__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Visit_Report__c/fields/Division_Multi__c.field-meta.xml
<CustomField>
    <fullName>Division_Multi__c</fullName>
    <label>Division</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit_Report__c/fields/Negative_feedback__c.field-meta.xml
<CustomField>
    <fullName>Negative_feedback__c</fullName>
    <label>Negative feedback</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Visit_Report__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Visit_Report__c/fields/Pain_Points__c.field-meta.xml
<CustomField>
    <fullName>Pain_Points__c</fullName>
    <label>Pain Points</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Visit_Report__c/fields/Positive_feedback__c.field-meta.xml
<CustomField>
    <fullName>Positive_feedback__c</fullName>
    <label>Positive feedback</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Visit_Report__c/fields/Reason_for_visit__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_visit__c</fullName>
    <label>Reason for visit</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit_Report__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Report__c/fields/Type_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Visit__c</fullName>
    <label>Type of Visit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Visit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Division.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PSD - Parts &amp; Services</fullName>
    </customValue>
    <customValue>
        <fullName>SRD - Surface</fullName>
    </customValue>
    <customValue>
        <fullName>TLD - Tools &amp; Attachments</fullName>
    </customValue>
    <customValue>
        <fullName>UMR - Underground</fullName>
    </customValue>
    <customValue>
        <fullName>TIN - Technology &amp; Innovation</fullName>
    </customValue>
    <customValue>
        <fullName>DSD - Digital Solutions Division</fullName>
    </customValue>
    <customValue>
        <fullName>Hydraulics</fullName>
        <isActive>false</isActive>
        <label>Hydraulics</label>
    </customValue>
    <customValue>
        <fullName>Technology &amp; Digital</fullName>
        <isActive>false</isActive>
        <label>Technology &amp; Digital</label>
    </customValue>
    <customValue>
        <fullName>All</fullName>
        <isActive>false</isActive>
        <label>All</label>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Type_of_Visit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business Review meeting</fullName>
    </customValue>
    <customValue>
        <fullName>Standard Sales Call/Site visit</fullName>
        <label>Standard Sales Call</label>
    </customValue>
    <customValue>
        <fullName>Site Visit</fullName>
    </customValue>
    <customValue>
        <fullName>Proposal presentation</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Type of Visit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Casepdf.cls
public class Casepdf {
    
    public Visit_Report__c values { get; private set; }
    
    public Casepdf(){
        values = [SELECT Id,Name,Account__r.Name,CreatedBy.Name,Agenda_of_visit__c,Reason_for_visit__c,Status__c,Division_Multi__c,
                  Subject__c,Date_Time__c,Type_of_Visit__c,Additional_attendance_to_the_meeting__c,Attendance_Contact_person_in_meeting__r.Name,
                  Description__c,Notes__c,Positive_feedback__c,Negative_feedback__c,Pain_Points__c,Accomplishments__c
                  FROM Visit_Report__c WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
        
    }
    public Visit_Report__c getVR() {
        return values;
    }
    
    public List<Task> getTasks() {
        List<Task> tasks = [SELECT Id, Subject, Owner.Name, ActivityDate, Status, Priority FROM Task WHERE WhatId = :ApexPages.currentPage().getParameters().get('id')];
        return tasks;
    }
}