force-app/main/default/objects/Visit_Report__c/Visit_Report__c.object-meta.xml
<CustomObject>
    <description>As a user I want to be able to add a visit report with all needed information So I can keep my visit notes in a structured way</description>
    <label>Visit Report</label>
    <nameField>
        <label>Visit Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Report__c/fields/Reason_for_visit__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_visit__c</fullName>
    <label>Reason for visit</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CasepdfTest.cls
@isTest

public class CasepdfTest {
    
    @testSetup
    public static void setup(){
        
        // Insert Visit Report
        Visit_Report__c rep = new Visit_Report__c(Name='Test Report', Reason_for_visit__c='Test');
        insert rep;
    }
    
    @isTest static void CasepdfTest(){
        
         List<Visit_Report__c> repList = [Select Id from Visit_Report__c Limit 1]; 
        
        PageReference pageRef = Page.visitReportPDF;
        Test.setCurrentPage(pageRef);
        
        // put the Visit Report id as a parameter
        ApexPages.currentPage().getParameters().put('id',repList[0].id);
  
        Test.startTest();
        Casepdf obj = new Casepdf();
        obj.getVR();
        Test.stopTest();
    }
    
}