force-app/main/default/objects/Account_plan_2_0__c/Account_plan_2_0__c.object-meta.xml
<CustomObject>
    <description>Object to store new version of account plans</description>
    <label>Account plan 2.0</label>
    <nameField>
        <label>Account plan 2.0 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account plans 2.0</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_plan_2_0__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account plans 2.0</relationshipLabel>
    <relationshipName>Account_plans_2_0</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Plan_Accounts__c/Account_Plan_Accounts__c.object-meta.xml
<CustomObject>
    <description>Junction object to store Accounts related with account plans</description>
    <label>Account Plan Accounts</label>
    <nameField>
        <label>Account plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Plan_Accounts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master detail relationship to Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plan Accounts</relationshipLabel>
    <relationshipName>Account_Plan_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Plan_Accounts__c/fields/Account_plan_2_0__c.field-meta.xml
<CustomField>
    <fullName>Account_plan_2_0__c</fullName>
    <label>Account plan 2.0</label>
    <referenceTo>Account_plan_2_0__c</referenceTo>
    <relationshipLabel>Account Plan Accounts</relationshipLabel>
    <relationshipName>Account_Plan_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Plan_Contacts__c/Account_Plan_Contacts__c.object-meta.xml
<CustomObject>
    <description>Junction object to store contacts related to account plans</description>
    <label>Account Plan Contacts</label>
    <nameField>
        <label>Account Plan Contacts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Plan_Contacts__c/fields/Account_plan_2_0__c.field-meta.xml
<CustomField>
    <fullName>Account_plan_2_0__c</fullName>
    <label>Account plan 2.0</label>
    <referenceTo>Account_plan_2_0__c</referenceTo>
    <relationshipLabel>Account Plan Contacts</relationshipLabel>
    <relationshipName>Account_Plan_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Plan_Contacts__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Master detail relationship to contacts object</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Account Plan Contacts</relationshipLabel>
    <relationshipName>Account_Plan_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Plan_Settings__mdt/Account_Plan_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata to set the account plan columns in the table</description>
    <label>Account Plan Settings</label>
    <pluralLabel>Account Plan Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Account_Plan_Settings__mdt/fields/Api_Fields_Name__c.field-meta.xml
<CustomField>
    <fullName>Api_Fields_Name__c</fullName>
    <description>Field to store api fields name to match with the columns</description>
    <inlineHelpText>Insert the api fields name in the same order as the columns.</inlineHelpText>
    <label>Api Fields Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Plan_Settings__mdt/fields/columns__c.field-meta.xml
<CustomField>
    <fullName>columns__c</fullName>
    <description>Columns names separated by coma</description>
    <inlineHelpText>Coma separated column names</inlineHelpText>
    <label>columns</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Plan_Settings__mdt/fields/is_Editable__c.field-meta.xml
<CustomField>
    <fullName>is_Editable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Editable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Plan_Settings__mdt/fields/object_name__c.field-meta.xml
<CustomField>
    <fullName>object_name__c</fullName>
    <description>api object name to retrieve and store the data</description>
    <inlineHelpText>insert api object name</inlineHelpText>
    <label>object name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Plan_Settings__mdt/fields/Tab_column__c.field-meta.xml
<CustomField>
    <fullName>Tab_column__c</fullName>
    <description>Field to store the header of the tab for this columns</description>
    <inlineHelpText>insert the tab name</inlineHelpText>
    <label>Tab column</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountPlanTableController.cls
public with sharing class AccountPlanTableController extends BaseController{
    
    // Get the Account Plan table settings
    @AuraEnabled
    public static Map<String, Object> getAccountPlanTableSettings(String tabName, Id recordId){
        Map<String, Object> result = getActionSuccessful(null);
        try{
            String objectName = '';
            String fieldsToQuery = '';
            Boolean isEditable = false;
            List<Account_Plan_Settings__mdt> accPlanSettings = [Select is_Editable__c, Tab_column__c, columns__c, object_name__c, Api_Fields_Name__c From Account_Plan_Settings__mdt where Tab_column__c = :tabName Limit 1];
            List<String> columnsList = new List<String>();
            
            for(Account_Plan_Settings__mdt accPlanSetting : accPlanSettings){
                for(String column : accPlanSetting.columns__c.split(',')){
                    columnsList.add(column);
                }
                objectName = accPlanSetting.object_name__c;
                fieldsToQuery = accPlanSetting.Api_Fields_Name__c;
                isEditable = accPlanSetting.is_Editable__c;
            }

            result.put('accPlanSettings', accPlanSettings);
            result.put('columnsList', columnsList);
            List<String> apiFieldsList = fieldsToQuery.split(','); 
            result.put('apiFieldsList', apiFieldsList);
            result.put('isEditable', isEditable);
            result.put('existingRecords', getExistingRecords(recordId, objectName, fieldsToQuery));
        }catch(Exception e) {
            result = getActionFailed(e);
        }
        return result;
    }

    @AuraEnabled
    public static Map<String, Object> createRecord(String objectTypeName, Id accountPlan){
        Map<String, Object> result = getActionSuccessful(null);
        try{
            String jsonObject = '{ "Account_plan_2_0__c": '+JSON.serialize(accountPlan)+'}';
            sObject mySObject;

            Type objectType = Type.forName(objectTypeName);
            mySObject = (sObject)objectType.newInstance();
            mySObject = (sObject)JSON.deserialize(jsonObject, objectType);
            insert mySObject;
        }catch(Exception e) {
            result = getActionFailed(e);
        }
        return result;
    }

    @AuraEnabled
    public static Map<String, Object> linkContact(Id accountPlanId, Id contactId){
        Map<String, Object> result = getActionSuccessful(null);
        try{
            List<Account_Plan_Contacts__c> accPlanContactsList = [Select Id From Account_Plan_Contacts__c where Account_plan_2_0__c = :accountPlanId AND Contact__c = :contactId];
            if(accPlanContactsList.size()>0){
                result = getActionFailed('Record already exists');
            }else{
                Account_Plan_Contacts__c acContact = new Account_Plan_Contacts__c(Account_plan_2_0__c = accountPlanId, Contact__c = contactId);
                insert acContact;
            }
        }catch(Exception e) {
            result = getActionFailed(e);
        }
        return result;
    }

    @AuraEnabled
    public static Map<String, Object> linkAccount(Id accountPlanId, Id accountId){
        Map<String, Object> result = getActionSuccessful(null);
        try{
            List<Account_Plan_Accounts__c> accPlanAccountsList = [Select Id From Account_Plan_Accounts__c where Account_plan_2_0__c = :accountPlanId AND Account__c = :accountId];
            if(accPlanAccountsList.size()>0){
                result = getActionFailed('Record already exists');
            }else{
                Account_Plan_Accounts__c acAccount = new Account_Plan_Accounts__c(Account_plan_2_0__c = accountPlanId, Account__c = accountId);
                insert acAccount;
            }
        }catch(Exception e) {
            result = getActionFailed(e);
        }
        return result;
    }

    @AuraEnabled
    public static Map<String, Object> deleteRecord(Id rowId, String objectTypeName){
        Map<String, Object> result = getActionSuccessful(null);
        try{
            sObject mySObject = Schema.getGlobalDescribe().get(objectTypeName).newSObject();
            mySObject.Id = rowId;
            delete mySObject;
        }catch(Exception e) {
            result = getActionFailed(e);
        }
        return result;
    }

    
    public static List<Object> getExistingRecords(Id recordId, String objectName, String fieldsToQuery){
        String query = 'SELECT ' + fieldsToQuery + ' FROM '+objectName+' Where Account_plan_2_0__c = \''+recordId+'\'';
        List<Object> recordsList = Database.query(query);
        return recordsList;
    }
}